# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4a1863f99ea5e3de4769d3bbf37199f57f2a4068dfcaf0cd4effadb5674dbbb61b1f04c645d515369e351c2fcaa303188bf75ab3efe1f66942cfc71488dac75

test:
  secret_key_base: bc247bd5e46b73afb76a67ec7bd0b31d5374a9bf4da03814076ef467777cd9f1870fae4e4bb61313813c755211b93ef6b930c78d6e4c266d9f315af3789905c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
